spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hoteldb
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update

okta:
  oauth2:
    issuer: https://dev-89351563.okta.com/oauth2/default
    client-id: 0oalge2s8iuMghBz45d7
    client-secret: A4EEssuIAgagrKBSzoWxjBjtvVrHvVDDfGxZaU2JB4rEFI3us7lfmZDGeaB1fRW_